version: "3.3"
volumes:
  mysql-data:
services:
  php:
    ports:
      - "8082:80"
    build:
      context: .
      dockerfile: ./environment/php/Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/var/cache
#    environment:
#      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_autostart=off  remote_port=9000"
#      PHP_IDE_CONFIG: "serverName=Docker_blog"

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysqlphp