version: "3.8"
volumes:
  mysql-data:
services:
  php:
    build:
      context: .
      dockerfile: ./environment/php/Dockerfile
    volumes:
      - ./www:/var/www/html
      - /var/www/html/var/cache

  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql

  #  httpd:
  #    ports:
  #      - "8082:80"
  #    depends_on:
  #      - php
  #    build:
  #      context: .
  #      dockerfile: ./environment/httpd/Dockerfile
  #    volumes:
  #      - ./www:/var/www/html
  #      - /var/www/html/var/cache

  nginx:
    build:
      context: .
      dockerfile: ./environment/nginx/Dockerfile
    #    command: [httpd-debug, '-g', 'daemon off;']
    volumes:
      - ./www:/var/www/html
    ports:
      - 8082:80
    depends_on:
      - php
