#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#  Symfony Froala WYSIWYG Editor
# https://froala.com/wysiwyg-editor/docs/framework-plugins/symfony/
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor
